AllCops:
  Exclude:
    - "bin/*"
    - "config/**/*"
    - "db/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "storage/**/*"
    - "temp/**/*"
    - "vendor/**/*"
    - "Gemfile"
    - "config.ru"


  # 新ルールを有効化
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false
